apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cicdapp
  name: cicdapp
spec:
        replicas: 1
  selector:
    matchLabels:
      app: cicdapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cicdapp
    spec:
      containers:
      - image: akshayb412/abhishek:50
        name: cicdapp
  
