apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdapp
  labels:
    app: cicdapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cicdapp
  template:
    metadata:
      labels:
        app: cicdapp
    spec:
      containers:
      - name: cicdapp
        image: akshayb412/abhishek:50
        ports:
        - containerPort: 8080
    
